BUCKET_CONFIGS = {
    # Major Cloud Storage Providers
    's3': {'type': 's3', 'provider': 'AWS', 'anonymous': True},
    'b2': {'type': 'b2', 'anonymous': True},
    'azureblob': {'type': 'azureblob', 'anonymous': True},
    'google_cloud_storage': {'type': 'google cloud storage', 'anonymous': True},
    'wasabi': {'type': 'wasabi', 'anonymous': True},
    'digitalocean': {'type': 's3', 'provider': 'DigitalOcean', 'anonymous': True},
    'cloudflare': {'type': 's3', 'provider': 'Cloudflare', 'anonymous': True},
    'cloudflare_r2': {'type': 's3', 'provider': 'Cloudflare R2', 'anonymous': True},
    'scaleway': {'type': 's3', 'provider': 'Scaleway', 'anonymous': True},
    'linode': {'type': 's3', 'provider': 'Linode', 'anonymous': True},
    'stackpath': {'type': 's3', 'provider': 'StackPath', 'anonymous': True},
    'idrive': {'type': 's3', 'provider': 'IDrive', 'anonymous': True},
    'ovh': {'type': 's3', 'provider': 'OVH', 'anonymous': True},
    'oracle': {'type': 's3', 'provider': 'Oracle', 'anonymous': True},
    'tencent': {'type': 's3', 'provider': 'Qcloud', 'anonymous': True},
    'alibaba': {'type': 's3', 'provider': 'Alibaba', 'anonymous': True},
    'minio': {'type': 's3', 'provider': 'Minio', 'anonymous': True},
    'ceph': {'type': 's3', 'provider': 'Ceph', 'anonymous': True},
    'arvancloud': {'type': 's3', 'provider': 'ArvanCloud', 'anonymous': True},
    'ionos': {'type': 's3', 'provider': 'Ionos', 'anonymous': True},
    'gcs': {'type': 'google cloud storage', 'anonymous': True},
    'huawei_obs': {'type': 'obs', 'provider': 'Huawei', 'anonymous': True},
    'ibm_cos': {'type': 's3', 'provider': 'IBM', 'anonymous': True},
    'vultr': {'type': 's3', 'provider': 'Vultr', 'anonymous': True},
    'netlify': {'type': 's3', 'provider': 'Netlify', 'anonymous': True},
    
    # File Protocols
    'ftp': {'type': 'ftp', 'host': '', 'user': '', 'pass': ''},
    'sftp': {'type': 'sftp', 'host': '', 'user': '', 'key_file': ''},
    'webdav': {'type': 'webdav', 'url': '', 'vendor': 'other', 'user': '', 'pass': ''},
    'smb': {'type': 'smb', 'host': '', 'user': '', 'pass': ''},
    'hdfs': {'type': 'hdfs', 'namenode': '', 'username': ''},
    
    # Cloud Services
    'dropbox': {'type': 'dropbox', 'token': ''},
    'onedrive': {'type': 'onedrive', 'drive_id': '', 'drive_type': 'business'},
    'googlephotos': {'type': 'google photos', 'client_id': '', 'client_secret': ''},
    'box': {'type': 'box', 'client_id': '', 'client_secret': ''},
    'pcloud': {'type': 'pcloud', 'client_id': '', 'client_secret': ''},
    'putio': {'type': 'putio', 'api_key': ''},
    'mailru': {'type': 'mailru', 'user': '', 'password': ''},
    'yandex': {'type': 'yandex', 'token': ''},
    'hidrive': {'type': 'hidrive', 'user': '', 'password': ''},
    'jottacloud': {'type': 'jottacloud', 'user': '', 'password': ''},
    'mega': {'type': 'mega', 'user': '', 'password': ''},
    'koofr': {'type': 'koofr', 'user': '', 'password': ''},
    'opendrive': {'type': 'opendrive', 'user': '', 'password': ''},
    'seafile': {'type': 'seafile', 'url': '', 'user': '', 'password': ''},
    'sugarSync': {'type': 'sugarsync', 'user': '', 'password': ''},
    'synology': {'type': 'webdav', 'vendor': 'synology', 'user': '', 'pass': ''},
    'nextcloud': {'type': 'webdav', 'vendor': 'nextcloud', 'user': '', 'pass': ''},

    # Regional Cloud Providers
    'yandex_storage': {'type': 's3', 'provider': 'Yandex', 'anonymous': True},
    'exoscale': {'type': 's3', 'provider': 'Exoscale', 'anonymous': True},
    'selectel': {'type': 's3', 'provider': 'Selectel', 'anonymous': True},
    'mail_ru_storage': {'type': 's3', 'provider': 'Mail.ru', 'anonymous': True},
    'naver_cloud': {'type': 's3', 'provider': 'Naver', 'anonymous': True},
    'kakao_cloud': {'type': 's3', 'provider': 'Kakao', 'anonymous': True},
    'leaseweb': {'type': 's3', 'provider': 'Leaseweb', 'anonymous': True},
    'upcloud': {'type': 's3', 'provider': 'UpCloud', 'anonymous': True},
    
    # Decentralized & Web3 Storage
    'ipfs': {'type': 'ipfs', 'provider': 'IPFS', 'anonymous': True},
    'filecoin': {'type': 'filecoin', 'provider': 'Filecoin', 'anonymous': True},
    'arweave': {'type': 'arweave', 'provider': 'Arweave', 'anonymous': True},
    'skynet': {'type': 'skynet', 'provider': 'Skynet', 'anonymous': True},
    'sia': {'type': 'sia', 'api_password': ''},
    'storj': {'type': 'storj', 'satellite': '', 'api_key': ''},
    'pinata': {'type': 'ipfs', 'provider': 'Pinata', 'anonymous': True},
    'web3_storage': {'type': 'ipfs', 'provider': 'Web3.Storage', 'anonymous': True},
    'nft_storage': {'type': 'ipfs', 'provider': 'NFT.Storage', 'anonymous': True},
    
    # Enterprise & Hybrid Storage
    'redhat_storage': {'type': 'swift', 'provider': 'RedHat', 'anonymous': True},
    'netapp_storage': {'type': 's3', 'provider': 'NetApp', 'anonymous': True},
    'dell_ecs': {'type': 's3', 'provider': 'Dell', 'anonymous': True},
    'hitachi_storage': {'type': 's3', 'provider': 'Hitachi', 'anonymous': True},
    'quantum': {'type': 's3', 'provider': 'Quantum', 'anonymous': True},
    'commvault': {'type': 's3', 'provider': 'Commvault', 'anonymous': True},
    
    # Specialized Storage
    '1fichier': {'type': 'fichier', 'api_key': ''},
    'akamai': {'type': 'netstorage', 'host': '', 'key': '', 'key_name': ''},
    'aliyun': {'type': 'oss', 'access_key_id': '', 'access_key_secret': ''},
    'chinaMobile': {'type': 'eos', 'access_key_id': '', 'access_key_secret': ''},
    'citrix': {'type': 'sharefile', 'client_id': '', 'client_secret': ''},
    'cloudinary': {'type': 'cloudinary', 'url': ''},
    'digistorage': {'type': 'digistorage', 'user': '', 'password': ''},
    'dreamhost': {'type': 's3', 'provider': 'Dreamhost', 'anonymous': True},
    'enterpriseFile': {'type': 'filefabric', 'url': '', 'user': '', 'password': ''},
    'fastmail': {'type': 'fastmail', 'user': '', 'password': ''},
    'filesCom': {'type': 'files.com', 'api_key': ''},
    'gofile': {'type': 'gofile', 'api_key': ''},
    'hetzner': {'type': 'hcloud', 'api_key': ''},
    'imageKit': {'type': 'imagekit', 'private_key': '', 'public_key': ''},
    'internetArchive': {'type': 'internetarchive', 'access_key': '', 'secret_key': ''},
    'leviia': {'type': 's3', 'provider': 'Leviia', 'anonymous': True},
    'liara': {'type': 's3', 'provider': 'Liara', 'anonymous': True},
    'magalu': {'type': 's3', 'provider': 'Magalu', 'anonymous': True},
    'memset': {'type': 's3', 'provider': 'Memset', 'anonymous': True},
    'petabox': {'type': 's3', 'provider': 'Petabox', 'anonymous': True},
    'pikpak': {'type': 'pikpak', 'user': '', 'password': ''},
    'pixeldrain': {'type': 'pixeldrain', 'api_key': ''},
    'premiumize': {'type': 'premiumize', 'api_key': ''},
    'proton': {'type': 'protondrive', 'user': '', 'password': ''},
    'qingstor': {'type': 'qingstor', 'access_key_id': '', 'secret_access_key': ''},
    'quatrix': {'type': 'quatrix', 'user': '', 'password': ''},
    'rackspace': {'type': 'rackspace', 'user': '', 'api_key': ''},
    'rsyncNet': {'type': 'rsync', 'user': '', 'password': ''},
    'seagate': {'type': 's3', 'provider': 'Seagate', 'anonymous': True},
    'uptobox': {'type': 'uptobox', 'access_token': ''},
    'zoho': {'type': 'zoho', 'client_id': '', 'client_secret': ''},
    'backblaze_b2': {'type': 'b2', 'provider': 'Backblaze', 'anonymous': True},
    'wasabi_hot': {'type': 's3', 'provider': 'Wasabi', 'anonymous': True},
    'filebase': {'type': 's3', 'provider': 'Filebase', 'anonymous': True},
    'fastly': {'type': 's3', 'provider': 'Fastly', 'anonymous': True},
    'gcore': {'type': 's3', 'provider': 'GCore', 'anonymous': True},
    'cdn77': {'type': 's3', 'provider': 'CDN77', 'anonymous': True},
    'bunny': {'type': 's3', 'provider': 'BunnyCDN', 'anonymous': True},
    'ddns': {'type': 's3', 'provider': 'DDNS', 'anonymous': True},
    'mega_nz': {'type': 'mega', 'provider': 'MEGA', 'anonymous': True},
}

PREFIX_TO_SERVICE = {
    # Cloud Storage Prefixes
    's3:': 's3',
    'b2:': 'b2',
    'azure:': 'azureblob',
    'gs:': 'google_cloud_storage',
    'do:': 'digitalocean',
    'cf:': 'cloudflare',
    'r2:': 'cloudflare_r2',
    'scw:': 'scaleway',
    'linode:': 'linode',
    'ovh:': 'ovh',
    'oracle:': 'oracle',
    'oss:': 'alibaba',
    'cos:': 'tencent',
    'minio:': 'minio',
    'ceph:': 'ceph',
    'arvan:': 'arvancloud',
    'ionos:': 'ionos',
    'gcs:': 'gcs',
    'obs:': 'huawei_obs',
    'ibm:': 'ibm_cos',
    'vultr:': 'vultr',
    'netlify:': 'netlify',
    
    # File Protocol Prefixes
    'ftp:': 'ftp',
    'sftp:': 'sftp',
    'webdav:': 'webdav',
    'smb:': 'smb',
    'hdfs:': 'hdfs',
    
    # Cloud Service Prefixes
    'dropbox:': 'dropbox',
    'onedrive:': 'onedrive',
    'googlephotos:': 'googlephotos',
    'box:': 'box',
    'pcloud:': 'pcloud',
    'putio:': 'putio',
    'mailru:': 'mailru',
    'yandex:': 'yandex',
    'hidrive:': 'hidrive',
    'jottacloud:': 'jottacloud',
    'mega:': 'mega',
    'koofr:': 'koofr',
    'opendrive:': 'opendrive',
    'seafile:': 'seafile',
    'sugarsync:': 'sugarSync',
    'nextcloud:': 'nextcloud',
    
    # Regional Provider Prefixes
    'yandex:': 'yandex_storage',
    'exoscale:': 'exoscale',
    'selectel:': 'selectel',
    'mailru-store:': 'mail_ru_storage',
    'naver:': 'naver_cloud',
    'kakao:': 'kakao_cloud',
    'leaseweb:': 'leaseweb',
    'upcloud:': 'upcloud',
    
    # Decentralized Storage Prefixes
    'ipfs:': 'ipfs',
    'filecoin:': 'filecoin',
    'arweave:': 'arweave',
    'skynet:': 'skynet',
    'sia:': 'sia',
    'storj:': 'storj',
    'pinata:': 'pinata',
    'web3:': 'web3_storage',
    'nftstorage:': 'nft_storage',
    
    # Enterprise & Hybrid Storage Prefixes
    'redhat:': 'redhat_storage',
    'netapp:': 'netapp_storage',
    'dell:': 'dell_ecs',
    'hitachi:': 'hitachi_storage',
    'quantum:': 'quantum',
    'commvault:': 'commvault',
    
    # Specialized Storage Prefixes
    '1fichier:': '1fichier',
    'akamai:': 'akamai',
    'aliyun:': 'aliyun',
    'chinamobile:': 'chinaMobile',
    'citrix:': 'citrix',
    'cloudinary:': 'cloudinary',
    'digistorage:': 'digistorage',
    'dreamhost:': 'dreamhost',
    'enterpriseFile:': 'enterpriseFile',
    'fastmail:': 'fastmail',
    'filesCom:': 'filesCom',
    'gofile:': 'gofile',
    'hetzner:': 'hetzner',
    'imageKit:': 'imageKit',
    'internetArchive:': 'internetArchive',
    'leiva:': 'leviia',
    'liara:': 'liara',
    'magalu:': 'magalu',
    'memset:': 'memset',
    'petabox:': 'petabox',
    'pikpak:': 'pikpak',
    'pixeldrain:': 'pixeldrain',
    'premiumize:': 'premiumize',
    'proton:': 'proton',
    'qingstor:': 'qingstor',
    'quatrix:': 'quatrix',
    'rackspace:': 'rackspace',
    'rsyncNet:': 'rsyncNet',
    'seagate:': 'seagate',
    'uptobox:': 'uptobox',
    'zoho:': 'zoho',
    'backblaze:': 'backblaze_b2',
    'wasabi:': 'wasabi_hot',
    'filebase:': 'filebase',
    'fastly:': 'fastly',
    'gcore:': 'gcore',
    'cdn77:': 'cdn77',
    'bunny:': 'bunny',
    'ddns:': 'ddns',
    'mega-nz:': 'mega_nz',
}